// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19dpxWm8DdQZJufurNNKysZ1kk1wfAXE',
    appId: '1:622597531367:web:0a73e77e6d092de54ee442',
    messagingSenderId: '622597531367',
    projectId: 'cajutel-e830f',
    authDomain: 'cajutel-e830f.firebaseapp.com',
    storageBucket: 'cajutel-e830f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOo20IPibe-kB87rO4VwGHqWlZxEFnLnE',
    appId: '1:622597531367:android:c98d70c04baac6094ee442',
    messagingSenderId: '622597531367',
    projectId: 'cajutel-e830f',
    storageBucket: 'cajutel-e830f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX7xEjMHsd7Da1oqYBCHoVN3Q_QNUf0xY',
    appId: '1:622597531367:ios:bebb81a3ebc54e004ee442',
    messagingSenderId: '622597531367',
    projectId: 'cajutel-e830f',
    storageBucket: 'cajutel-e830f.firebasestorage.app',
    iosBundleId: 'com.example.cajutelApp',
  );
}
